# -*- coding: utf-8 -*-
"""analyse_corpus_pole_emploi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tsdks94oCzQifjfBSTufjvjw18lcVAgG

# 📊 Analyse du corpus d'offres d'emploi Pôle Emploi
Ce notebook couvre toutes les étapes d'analyse textuelle :
- Distribution et structure du corpus
- Qualité et anomalies textuelles
- Analyse lexicale (TF-IDF, wordclouds)
- Détection de doublons
- Projection UMAP / t-SNE

---
## 📦 Bloc 0 — Imports
"""

# ── Manipulation de données ──────────────────────────────────────────────────
import pandas as pd
import numpy as np
import re

# ── Visualisation ────────────────────────────────────────────────────────────
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from wordcloud import WordCloud

# ── NLP ──────────────────────────────────────────────────────────────────────
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.corpus import stopwords

# ── Réduction de dimension ───────────────────────────────────────────────────
from sklearn.manifold import TSNE
# umap-learn doit être installé : pip install umap-learn
try:
    import umap
    UMAP_AVAILABLE = True
except ImportError:
    UMAP_AVAILABLE = False
    print("UMAP non disponible. Installe-le avec : pip install umap-learn")

# ── Téléchargement des stopwords français ────────────────────────────────────
nltk.download('stopwords', quiet=True)
STOPWORDS_FR = set(stopwords.words('french'))

# ── Style global des graphiques matplotlib ───────────────────────────────────
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams['figure.dpi'] = 120
plt.rcParams['figure.figsize'] = (12, 5)

print("✅ Tous les imports sont OK")

"""---
## 📂 Bloc 1 — Chargement du corpus
"""

# ── Chargement depuis Hugging Face ──────────────────────────────────────────
from datasets import load_dataset

# Télécharge le dataset depuis le Hub
ds = load_dataset("oscarfossey/NLP_Pole_emploi")

# ── Vérification des splits disponibles ─────────────────────────────────────
print("Splits disponibles :", list(ds.keys()))
for split in ds.keys():
    print(f"  {split} → {len(ds[split])} offres")

# ── Conversion de chaque split en DataFrame ──────────────────────────────────
df_train = ds["train"].to_pandas()
df_val   = ds["validation"].to_pandas()
df_test  = ds["test"].to_pandas()

# ── Ajout d'une colonne pour savoir d'où vient chaque offre ──────────────────
# Utile pour vérifier que les 3 splits ont la même distribution
df_train["split"] = "train"
df_val["split"]   = "validation"
df_test["split"]  = "test"

# ── Fusion des 3 splits en un seul DataFrame pour l'analyse ─────────────────
df = pd.concat([df_train, df_val, df_test], ignore_index=True)

# ── Aperçu global ────────────────────────────────────────────────────────────
print(f"\nCorpus complet   : {len(df)} offres")
print(f"Colonnes         : {list(df.columns)}")
print(f"\nRépartition des splits :")
print(df["split"].value_counts())
print(f"\nValeurs nulles :\n{df.isnull().sum()}\n")
df.head(3)

"""---
## 📊 Bloc 2 — Distribution des offres par catégorie
"""

# ── Nombre de valeurs uniques par niveau hiérarchique ────────────────────────

print(f"Nombre de sub_categories     : {df['sub_categorie'].nunique()}")
print(f"Nombre de sub_sub_categories : {df['sub_sub_categorie'].nunique()}")
print(f"Nombre de names              : {df['name'].nunique()}")

# ── Détail : nombre d'occurrences par valeur ─────────────────────────────────
print("\n── Distribution sub_categorie ──")
print(df['sub_categorie'].value_counts())

print("\n── Distribution sub_sub_categorie ──")
print(df['sub_sub_categorie'].value_counts())

print("\n── Distribution name ──")
print(df['name'].value_counts())

# ── Visualisation du déséquilibre des 3 niveaux hiérarchiques ────────────────

fig, axes = plt.subplots(1, 2, figsize=(18, 5))

# ── sub_categorie ────────────────────────────────────────────────────────────
counts_sub = df['sub_categorie'].value_counts()
axes[0].bar(counts_sub.index.astype(str), counts_sub.values, color='steelblue')
axes[0].set_title(f"sub_categorie ({df['sub_categorie'].nunique()} classes)", fontsize=12)
axes[0].set_xlabel("Code sub_categorie")
axes[0].set_ylabel("Nombre d'offres")
axes[0].tick_params(axis='x', rotation=90)

# ── sub_sub_categorie ────────────────────────────────────────────────────────
counts_subsub = df['sub_sub_categorie'].value_counts()
axes[1].bar(counts_subsub.index.astype(str), counts_subsub.values, color='coral')
axes[1].set_title(f"sub_sub_categorie ({df['sub_sub_categorie'].nunique()} classes)", fontsize=12)
axes[1].set_xlabel("Code sub_sub_categorie")
axes[1].set_ylabel("Nombre d'offres")
axes[1].tick_params(axis='x', rotation=90)

# ── Nombre d'offres par catégorie principale ─────────────────────────────────
counts = df['categorie'].value_counts().reset_index()
counts.columns = ['categorie', 'nb_offres']

fig, ax = plt.subplots(figsize=(14, 5))
sns.barplot(data=counts, x='categorie', y='nb_offres', ax=ax)
ax.set_title("Nombre d'offres par catégorie", fontsize=14)
ax.set_xlabel("Catégorie")
ax.set_ylabel("Nombre d'offres")
ax.tick_params(axis='x', rotation=45)
plt.tight_layout()
plt.show()

# ── Ratio déséquilibre : classe majoritaire vs minoritaire ───────────────────
ratio = counts['nb_offres'].max() / counts['nb_offres'].min()
print(f"Ratio déséquilibre (max/min) : {ratio:.1f}x")
print("→ Si > 5x, le corpus est fortement déséquilibré")

# ── Treemap interactif : catégorie → sub_categorie ───────────────────────────
# Utile pour voir la hiérarchie d'un coup d'œil
fig = px.treemap(
    df,
    path=['categorie', 'sub_categorie'],  # hiérarchie des niveaux
    title="Treemap : répartition catégorie → sous-catégorie"
)
fig.update_layout(margin=dict(t=40, l=0, r=0, b=0))
fig.show()

# ── Sunburst interactif : hiérarchie complète sur 3 niveaux ─────────────────
fig = px.sunburst(
    df,
    path=['categorie', 'sub_categorie', 'sub_sub_categorie'],
    title="Sunburst : hiérarchie complète des catégories"
)
fig.update_layout(margin=dict(t=40, l=0, r=0, b=0))
fig.show()

# ── Vérification de la cohérence des labels hiérarchiques ───────────────────
# On vérifie qu'une sub_categorie n'appartient pas à plusieurs catégories
incoherences = (
    df.groupby('sub_categorie')['categorie']
    .nunique()
    .reset_index()
    .rename(columns={'categorie': 'nb_categories_parentes'})
)
problemes = incoherences[incoherences['nb_categories_parentes'] > 1]

print(f"Sous-catégories incohérentes (multi-parentes) : {len(problemes)}")
if len(problemes) > 0:
    print(problemes)

"""---
## 📏 Bloc 3 — Distribution de la longueur des textes
"""

# ── Histogramme global de text_length ───────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Distribution brute
axes[0].hist(df['text_length'], bins=50, color='steelblue', edgecolor='white')
axes[0].set_title("Distribution de la longueur des textes")
axes[0].set_xlabel("Nombre de caractères")
axes[0].set_ylabel("Fréquence")

# Distribution en log (plus lisible si longue queue à droite)
axes[1].hist(df['text_length'], bins=50, color='coral', edgecolor='white', log=True)
axes[1].set_title("Distribution (échelle log)")
axes[1].set_xlabel("Nombre de caractères")
axes[1].set_ylabel("Fréquence (log)")

plt.tight_layout()
plt.show()

# ── Statistiques descriptives ────────────────────────────────────────────────
print(df['text_length'].describe().round(0))

# ── Boxplot de text_length par catégorie ─────────────────────────────────────
# Permet de comparer les catégories entre elles
fig, ax = plt.subplots(figsize=(14, 6))
sns.boxplot(
    data=df,
    x='categorie',
    y='text_length',
    ax=ax,
    showfliers=False   # on cache les outliers extrêmes pour la lisibilité
)
ax.set_title("Longueur des textes par catégorie", fontsize=14)
ax.set_xlabel("Catégorie")
ax.set_ylabel("Longueur (caractères)")
ax.tick_params(axis='x', rotation=45)
plt.tight_layout()
plt.show()

# ── Identification des textes trop courts (< 100 caractères) ─────────────────
seuil_court = 100
textes_courts = df[df['text_length'] < seuil_court]
print(f"Offres avec moins de {seuil_court} caractères : {len(textes_courts)} "
      f"({100*len(textes_courts)/len(df):.1f}%)")
textes_courts[['name', 'categorie', 'text_length', 'textual description']].head()

"""---
## 🔴 Bloc 4 — Détection des anomalies textuelles
"""

# ── Calcul de plusieurs indicateurs d'anomalie ───────────────────────────────
texte = df['textual description'].fillna('')   # on remplace les NaN par une chaîne vide

# Taux de majuscules (% de lettres qui sont en majuscules)
df['taux_majuscules'] = texte.apply(
    lambda t: sum(1 for c in t if c.isupper()) / max(len(t), 1)
)

# Présence de balises HTML résiduelles (ex : <br>, <p>, &nbsp;)
df['a_balises_html'] = texte.str.contains(r'<[a-z]+>|&[a-z]+;', regex=True)

# Présence de caractères spéciaux inhabituels
df['a_chars_speciaux'] = texte.str.contains(r'[|#*$€\\@\[\]{}]', regex=True)

# Texte vide ou NaN
df['texte_vide'] = df['textual description'].isnull() | (texte.str.strip() == '')

# ── Résumé des anomalies ─────────────────────────────────────────────────────
anomalies = {
    'Textes vides / NaN'       : df['texte_vide'].sum(),
    'Balises HTML résiduelles' : df['a_balises_html'].sum(),
    'Caractères spéciaux'      : df['a_chars_speciaux'].sum(),
    'Taux majuscules > 30%'    : (df['taux_majuscules'] > 0.30).sum(),
    'Taux majuscules > 50%'    : (df['taux_majuscules'] > 0.50).sum(),
    'Textes < 100 caractères'  : (df['text_length'] < 100).sum(),
}
resume = pd.DataFrame.from_dict(
    anomalies, orient='index', columns=['nb_offres']
)
resume['% du corpus'] = (resume['nb_offres'] / len(df) * 100).round(2)
print(resume)

# ── Visualisation du résumé des anomalies (barres horizontales) ──────────────
fig, ax = plt.subplots(figsize=(10, 5))
ax.barh(resume.index, resume['% du corpus'], color='salmon', edgecolor='white')
ax.set_xlabel("% du corpus")
ax.set_title("Synthèse des anomalies textuelles", fontsize=14)
for i, v in enumerate(resume['% du corpus']):
    ax.text(v + 0.1, i, f"{v:.1f}%", va='center', fontsize=10)
plt.tight_layout()
plt.show()

# ── Scatter plot : longueur vs taux de majuscules ────────────────────────────
# Les points en haut à gauche (courts + beaucoup de majuscules) sont suspects
fig, ax = plt.subplots(figsize=(10, 5))
scatter = ax.scatter(
    df['text_length'],
    df['taux_majuscules'],
    alpha=0.3,
    s=8,
    c=df['taux_majuscules'],
    cmap='RdYlGn_r'
)
ax.axhline(0.30, color='red', linestyle='--', linewidth=1, label='Seuil 30% majuscules')
ax.set_xlabel("Longueur du texte (caractères)")
ax.set_ylabel("Taux de majuscules")
ax.set_title("Longueur vs taux de majuscules", fontsize=14)
ax.legend()
plt.colorbar(scatter, ax=ax, label='Taux majuscules')
plt.tight_layout()
plt.show()

"""---
## 🔤 Bloc 5 — Analyse lexicale : TF-IDF et wordclouds
"""

# ── Calcul du TF-IDF global sur tout le corpus ───────────────────────────────
vectorizer = TfidfVectorizer(
    stop_words=list(STOPWORDS_FR),
    max_features=5000,
    min_df=3,            # un mot doit apparaître dans au moins 3 offres
    ngram_range=(1, 2)   # on inclut les bigrammes (ex : "chef projet")
)
tfidf_matrix = vectorizer.fit_transform(df['textual description'].fillna(''))
vocab = vectorizer.get_feature_names_out()

print(f"Taille de la matrice TF-IDF : {tfidf_matrix.shape}")
print(f"Vocabulaire : {len(vocab)} termes")

# ── Top 20 termes TF-IDF les plus discriminants par catégorie ────────────────
# Pour chaque catégorie, on calcule le score TF-IDF moyen de chaque terme
categories = df['categorie'].unique()

fig, axes = plt.subplots(
    nrows=(len(categories) + 1) // 2,
    ncols=2,
    figsize=(16, 4 * ((len(categories) + 1) // 2))
)
axes = axes.flatten()

for i, cat in enumerate(categories):
    # Indices des lignes de cette catégorie
    idx = df[df['categorie'] == cat].index
    # Score TF-IDF moyen pour cette catégorie
    scores_cat = np.asarray(tfidf_matrix[idx].mean(axis=0)).flatten()
    top20_idx = scores_cat.argsort()[-20:][::-1]
    top20_mots = [vocab[j] for j in top20_idx]
    top20_scores = scores_cat[top20_idx]

    axes[i].barh(top20_mots[::-1], top20_scores[::-1], color='steelblue')
    axes[i].set_title(f"Top TF-IDF — {cat}", fontsize=11)
    axes[i].set_xlabel("Score moyen")

# Cache les sous-graphes vides s'il y en a
for j in range(len(categories), len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Termes les plus discriminants par catégorie (TF-IDF)", fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# ── Wordclouds par catégorie ──────────────────────────────────────────────────
# Un wordcloud par catégorie basé sur les scores TF-IDF
fig, axes = plt.subplots(
    nrows=(len(categories) + 1) // 2,
    ncols=2,
    figsize=(16, 5 * ((len(categories) + 1) // 2))
)
axes = axes.flatten()

for i, cat in enumerate(categories):
    idx = df[df['categorie'] == cat].index
    scores_cat = np.asarray(tfidf_matrix[idx].mean(axis=0)).flatten()
    # Dictionnaire mot → score pour le wordcloud
    freq_dict = {vocab[j]: float(scores_cat[j]) for j in range(len(vocab)) if scores_cat[j] > 0}

    wc = WordCloud(
        width=800, height=400,
        background_color='white',
        max_words=80,
        colormap='Blues'
    ).generate_from_frequencies(freq_dict)

    axes[i].imshow(wc, interpolation='bilinear')
    axes[i].axis('off')
    axes[i].set_title(f"Wordcloud — {cat}", fontsize=12)

for j in range(len(categories), len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Wordclouds TF-IDF par catégorie", fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

"""---
## 📐 Bloc 6 — Richesse lexicale (Type-Token Ratio)
"""

# ── Le TTR mesure la diversité du vocabulaire dans chaque offre ──────────────
# TTR = nb de mots uniques / nb total de mots
# Un TTR élevé = texte varié ; un TTR faible = texte répétitif

def calcul_ttr(texte):
    """Calcule le Type-Token Ratio d'un texte."""
    mots = re.findall(r'\b\w+\b', str(texte).lower())
    if len(mots) == 0:
        return 0
    return len(set(mots)) / len(mots)

df['ttr'] = df['textual description'].apply(calcul_ttr)

# ── Histogramme du TTR global ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(df['ttr'], bins=40, color='mediumseagreen', edgecolor='white')
ax.axvline(df['ttr'].median(), color='red', linestyle='--', label=f"Médiane : {df['ttr'].median():.2f}")
ax.set_title("Distribution du Type-Token Ratio (richesse lexicale)", fontsize=13)
ax.set_xlabel("TTR (0 = très répétitif, 1 = très varié)")
ax.set_ylabel("Fréquence")
ax.legend()
plt.tight_layout()
plt.show()

# ── TTR moyen par catégorie ───────────────────────────────────────────────────
print(df.groupby('categorie')['ttr'].mean().sort_values(ascending=False).round(3))

# ── Nombre de tokens par offre ───────────────────────────────────────────────
df['nb_tokens'] = df['textual description'].fillna('').apply(
    lambda t: len(re.findall(r'\b\w+\b', t.lower()))
)

fig, ax = plt.subplots(figsize=(10, 4))
sns.boxplot(data=df, x='categorie', y='nb_tokens', ax=ax, showfliers=False)
ax.set_title("Nombre de tokens par catégorie", fontsize=13)
ax.set_xlabel("Catégorie")
ax.set_ylabel("Nombre de tokens")
ax.tick_params(axis='x', rotation=45)
plt.tight_layout()
plt.show()

# ── Statistiques globales ────────────────────────────────────────────────────
print("Vocabulaire total (mots uniques dans tout le corpus) :")
tous_les_mots = ' '.join(df['textual description'].fillna(''))
mots_uniques = set(re.findall(r'\b\w+\b', tous_les_mots.lower()))
print(f"  → {len(mots_uniques):,} mots uniques")
print(f"  → {len(re.findall(r'\b\w+\b', tous_les_mots)):,} mots au total")

"""---
## 🔁 Bloc 7 — Détection des quasi-doublons
"""

# ── Calcul de similarité cosine sur un échantillon ───────────────────────────
# On travaille sur un échantillon pour éviter les calculs trop lourds
TAILLE_ECHANTILLON = min(500, len(df))   # augmente si ton corpus n'est pas trop grand
echantillon = df.sample(TAILLE_ECHANTILLON, random_state=42)

# Vectorisation TF-IDF de l'échantillon
vec_doublons = TfidfVectorizer(
    stop_words=list(STOPWORDS_FR),
    max_features=3000
)
mat_ech = vec_doublons.fit_transform(echantillon['textual description'].fillna(''))

# Calcul de la matrice de similarité cosine
sim_matrix = cosine_similarity(mat_ech)
np.fill_diagonal(sim_matrix, 0)   # on ignore la similarité d'un texte avec lui-même

print(f"Matrice de similarité calculée : {sim_matrix.shape}")

# ── Heatmap de similarité (sous-échantillon de 50 offres pour la lisibilité) ─
N_HEATMAP = min(1000, TAILLE_ECHANTILLON)

fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(
    sim_matrix[:N_HEATMAP, :N_HEATMAP],
    cmap='Reds',
    vmin=0, vmax=1,
    ax=ax,
    xticklabels=False,
    yticklabels=False
)
ax.set_title(f"Heatmap de similarité cosine (sous-échantillon {N_HEATMAP} offres)", fontsize=13)
plt.tight_layout()
plt.show()

# ── Comptage des quasi-doublons (similarité > seuil) ─────────────────────────
SEUIL_DOUBLON = 0.85

# On prend le triangle supérieur pour éviter de compter les paires deux fois
tri_sup = np.triu(sim_matrix, k=1)
nb_quasi_doublons = (tri_sup > SEUIL_DOUBLON).sum()

print(f"Paires d'offres avec similarité > {SEUIL_DOUBLON} : {nb_quasi_doublons}")
print(f"(sur l'échantillon de {TAILLE_ECHANTILLON} offres)")
print("→ Ces paires sont des quasi-doublons potentiels")

# ── Distribution des scores de similarité maximale par offre ─────────────────
sim_max_par_offre = sim_matrix.max(axis=1)

fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(sim_max_par_offre, bins=40, color='tomato', edgecolor='white')
ax.axvline(SEUIL_DOUBLON, color='black', linestyle='--', label=f'Seuil doublon ({SEUIL_DOUBLON})')
ax.set_title("Similarité maximale de chaque offre avec les autres", fontsize=13)
ax.set_xlabel("Score de similarité cosine")
ax.set_ylabel("Nombre d'offres")
ax.legend()
plt.tight_layout()
plt.show()

"""---
## 🗺️ Bloc 8 — Projection 2D : t-SNE et UMAP
"""

# ── Projection t-SNE ─────────────────────────────────────────────────────────
# On réduit la matrice TF-IDF à 2 dimensions pour visualiser les clusters
# Attention : t-SNE peut être lent sur de grands corpus (utilise un échantillon)

N_TSNE = min(10000, len(df))   # augmente si possible
echantillon_tsne = df.sample(N_TSNE, random_state=42)

vec_tsne = TfidfVectorizer(stop_words=list(STOPWORDS_FR), max_features=2000)
mat_tsne = vec_tsne.fit_transform(echantillon_tsne['textual description'].fillna(''))

# Réduction à 2D avec t-SNE
print("Calcul t-SNE en cours (peut prendre quelques secondes)...")
tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=500)
coords_tsne = tsne.fit_transform(mat_tsne.toarray())

# Ajout des coordonnées au dataframe de l'échantillon
echantillon_tsne = echantillon_tsne.copy()
echantillon_tsne['tsne_x'] = coords_tsne[:, 0]
echantillon_tsne['tsne_y'] = coords_tsne[:, 1]

print("✅ t-SNE calculé")

# ── Palette de couleurs très différentiables ────────────────────────────────
# On définit manuellement des couleurs bien contrastées (évite les dégradés proches)
PALETTE = [
    "#E63946",  # rouge vif
    "#2196F3",  # bleu
    "#2DC653",  # vert
    "#FF9800",  # orange
    "#9C27B0",  # violet
    "#00BCD4",  # cyan
    "#FF4081",  # rose
    "#8BC34A",  # vert clair
    "#795548",  # marron
    "#607D8B",  # gris bleu
    "#FFEB3B",  # jaune
    "#FF5722",  # orange foncé
]

# On associe une couleur à chaque catégorie
categories_uniques = echantillon_tsne["categorie"].unique()
couleur_par_cat = {cat: PALETTE[i % len(PALETTE)] for i, cat in enumerate(categories_uniques)}

# ── Visualisation t-SNE colorée par catégorie ────────────────────────────────
fig = px.scatter(
    echantillon_tsne,
    x="tsne_x",
    y="tsne_y",
    color="categorie",
    color_discrete_map=couleur_par_cat,
    hover_data=["name", "code_rome"],
    title=f"Projection t-SNE des offres (n={N_TSNE}) — colorées par catégorie",
    opacity=0.8,
    width=950, height=650
)
fig.update_traces(marker_size=6)
fig.update_layout(
    legend_title="Catégorie",
    legend=dict(itemsizing="constant"),  # taille uniforme dans la légende
    plot_bgcolor="#F8F9FA",              # fond légèrement grisé pour mieux voir les points
    paper_bgcolor="white"
)
fig.update_xaxes(showgrid=True, gridcolor="#E0E0E0")
fig.update_yaxes(showgrid=True, gridcolor="#E0E0E0")
fig.show()

print("Si les points de même couleur sont regroupés → le corpus est bien séparable.")
print("Si tout est mélangé → les catégories ont des textes trop similaires.")

# ── Échantillon + vectorisation TF-IDF (commun aux deux graphiques) ──────────

N = 30000
ech = df.sample(min(N, len(df)), random_state=42).copy()

vec = TfidfVectorizer(
    stop_words=list(STOPWORDS_FR),
    max_features=3000,
    min_df=2
)
mat = vec.fit_transform(ech['textual description'].fillna(''))

print("Calcul t-SNE en cours...")
tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=40,
    n_iter=1000,
    n_jobs=-1
)
coords = tsne.fit_transform(mat.toarray())

ech['tsne_x'] = coords[:, 0]
ech['tsne_y'] = coords[:, 1]
print("✅ t-SNE calculé")

# ── T-SNE coloré par code_rome ───────────────────────────────────────────────
# Les codes_rome qui commencent par la même lettre ont la même couleur de base
# ex : tous les "I****" sont dans les tons bleus, tous les "A****" en rouges, etc.

# ── Couleur de base par lettre (1 teinte par domaine) ────────────────────────
COULEUR_PAR_LETTRE = {
    'A': '#E63946',  # rouge       → Agriculture
    'B': '#FF7043',  # orange foncé → Arts
    'C': '#FF9800',  # orange       → Banque
    'D': '#FFEB3B',  # jaune        → Commerce
    'E': '#8BC34A',  # vert clair   → Communication
    'F': '#2DC653',  # vert         → Construction
    'G': '#00BCD4',  # cyan         → Distribution
    'H': '#2196F3',  # bleu         → Industrie
    'I': '#3F51B5',  # bleu foncé   → Installation
    'J': '#9C27B0',  # violet       → Santé
    'K': '#E91E63',  # rose foncé   → Services
    'L': '#F06292',  # rose clair   → Spectacle
    'M': '#795548',  # marron       → Support
    'N': '#607D8B',  # gris bleu    → Transport
}

# ── Génération de la palette : une nuance différente par code_rome ────────────
# On fait varier la luminosité au sein de chaque groupe de lettres
import colorsys

def hex_to_rgb(h):
    """Convertit un code hex en tuple RGB (0-1)."""
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) / 255 for i in (0, 2, 4))

def rgb_to_hex(r, g, b):
    """Convertit un tuple RGB (0-1) en code hex."""
    return '#{:02x}{:02x}{:02x}'.format(int(r*255), int(g*255), int(b*255))

def varier_luminosite(hex_base, n, index):
    """
    Génère n nuances d'une couleur de base en faisant varier la luminosité.
    index = position du code dans son groupe (0, 1, 2...)
    """
    r, g, b = hex_to_rgb(hex_base)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    # On fait varier la luminosité entre 30% et 70%
    if n == 1:
        l_new = 0.50
    else:
        l_new = 0.30 + (index / (n - 1)) * 0.40
    r2, g2, b2 = colorsys.hls_to_rgb(h, l_new, s)
    return rgb_to_hex(r2, g2, b2)

# ── Construction du dictionnaire couleur par code_rome ───────────────────────
# On groupe les codes par leur première lettre
from collections import defaultdict
groupes = defaultdict(list)
for code in sorted(ech['code_rome'].unique()):
    lettre = str(code)[0].upper()
    groupes[lettre].append(code)

# Pour chaque groupe, on génère des nuances différentes
couleurs_rome = {}
for lettre, codes in groupes.items():
    hex_base = COULEUR_PAR_LETTRE.get(lettre, '#9E9E9E')  # gris par défaut
    for i, code in enumerate(codes):
        couleurs_rome[code] = varier_luminosite(hex_base, len(codes), i)

print("Couleurs générées pour", len(couleurs_rome), "code_rome")
print("Groupes par lettre :", {k: len(v) for k, v in groupes.items()})

# ── Affichage t-SNE par code_rome ─────────────────────────────────────────────

# On ajoute la lettre du domaine pour mieux lire la légende
ech['domaine'] = ech['code_rome'].astype(str).str[0].str.upper()

fig = px.scatter(
    ech,
    x='tsne_x',
    y='tsne_y',
    color='code_rome',
    color_discrete_map=couleurs_rome,
    hover_data=['name', 'categorie', 'sub_categorie', 'domaine'],
    title=f"T-SNE par code_rome — même lettre = même teinte (n={len(ech)})",
    opacity=0.75,
    width=1100, height=750
)
fig.update_traces(marker_size=3)
fig.update_layout(
    plot_bgcolor='#F8F9FA',
    paper_bgcolor='white',
    legend_title='code_rome',
    legend=dict(
        itemsizing='constant',
        font=dict(size=8),
        tracegroupgap=1
    )
)
fig.update_xaxes(showgrid=True, gridcolor='#E0E0E0', zeroline=False)
fig.update_yaxes(showgrid=True, gridcolor='#E0E0E0', zeroline=False)
fig.show()

# ── 26 couleurs manuellement choisies pour maximiser le contraste ─────────────
# Une couleur par sub_categorie, toutes bien distinctes visuellement

PALETTE_26 = [
    "#E63946",  # rouge vif
    "#2196F3",  # bleu
    "#2DC653",  # vert
    "#FF9800",  # orange
    "#9C27B0",  # violet
    "#00BCD4",  # cyan
    "#FF4081",  # rose vif
    "#8BC34A",  # vert clair
    "#795548",  # marron
    "#FF5722",  # orange foncé
    "#3F51B5",  # bleu indigo
    "#009688",  # teal
    "#FFEB3B",  # jaune
    "#F06292",  # rose clair
    "#1DE9B6",  # turquoise
    "#D500F9",  # violet fluo
    "#FF6D00",  # orange brûlé
    "#00E676",  # vert fluo
    "#2979FF",  # bleu électrique
    "#C6FF00",  # jaune vert
    "#FF1744",  # rouge foncé
    "#00B0FF",  # bleu ciel
    "#76FF03",  # vert lime
    "#F50057",  # rose fuchsia
    "#FFAB00",  # ambre
    "#6200EA",  # violet profond
]

# ── Association couleur → sub_categorie (triées pour que ce soit reproductible)
sous_cats = sorted(ech['sub_categorie'].unique())
print(f"Nombre de sub_categories : {len(sous_cats)}")

couleurs_subcat = {
    str(cat): PALETTE_26[i]
    for i, cat in enumerate(sous_cats)
}

# ── T-SNE coloré par sub_categorie ───────────────────────────────────────────
ech['sub_categorie_str'] = ech['sub_categorie'].astype(str)

fig = px.scatter(
    ech,
    x='tsne_x',
    y='tsne_y',
    color='sub_categorie_str',
    color_discrete_map=couleurs_subcat,
    hover_data=['name', 'code_rome', 'categorie'],
    title=f"T-SNE par sub_categorie — 26 couleurs distinctes (n={len(ech)})",
    opacity=0.75,
    width=1100, height=750,
    category_orders={'sub_categorie_str': [str(c) for c in sous_cats]}  # légende triée
)
fig.update_traces(marker_size=3)
fig.update_layout(
    plot_bgcolor='#F8F9FA',
    paper_bgcolor='white',
    legend_title='sub_categorie',
    legend=dict(
        itemsizing='constant',
        font=dict(size=10),
        tracegroupgap=2
    )
)
fig.update_xaxes(showgrid=True, gridcolor='#E0E0E0', zeroline=False)
fig.update_yaxes(showgrid=True, gridcolor='#E0E0E0', zeroline=False)
fig.show()

# ── Projection UMAP (si disponible) ──────────────────────────────────────────
# UMAP est généralement plus rapide et préserve mieux la structure globale

if UMAP_AVAILABLE:
    print("Calcul UMAP en cours...")
    reducer = umap.UMAP(
        n_components=2,
        random_state=42,
        n_neighbors=15,
        min_dist=0.1
    )
    coords_umap = reducer.fit_transform(mat_tsne.toarray())

    echantillon_tsne['umap_x'] = coords_umap[:, 0]
    echantillon_tsne['umap_y'] = coords_umap[:, 1]

    fig = px.scatter(
        echantillon_tsne,
        x='umap_x',
        y='umap_y',
        color='categorie',
        hover_data=['name', 'code_rome'],
        title=f"Projection UMAP des offres (n={N_TSNE}) — colorées par catégorie",
        opacity=0.7,
        width=900, height=600
    )
    fig.update_traces(marker_size=5)
    fig.update_layout(legend_title='Catégorie')
    fig.show()
else:
    print("UMAP non disponible. Installe-le avec : pip install umap-learn")

"""---
## 📋 Bloc 9 — Tableau de bord récapitulatif du corpus
"""

# ── Synthèse finale : un tableau récapitulatif de la qualité du corpus ────────
synthese = pd.DataFrame({
    'Indicateur': [
        'Nombre total d\'offres',
        'Nombre de catégories',
        'Nombre de code_rome uniques',
        'Longueur médiane (caractères)',
        'Longueur médiane (tokens)',
        'TTR médian',
        'Textes vides / NaN (%)',
        'Textes < 100 caractères (%)',
        'Offres avec balises HTML (%)',
        'Offres taux majuscules > 30% (%)',
        'Taille du vocabulaire unique',
    ],
    'Valeur': [
        len(df),
        df['categorie'].nunique(),
        df['code_rome'].nunique(),
        df['text_length'].median(),
        df['nb_tokens'].median(),
        round(df['ttr'].median(), 3),
        round(df['texte_vide'].mean() * 100, 2),
        round((df['text_length'] < 100).mean() * 100, 2),
        round(df['a_balises_html'].mean() * 100, 2),
        round((df['taux_majuscules'] > 0.30).mean() * 100, 2),
        len(mots_uniques),
    ]
})

print(synthese.to_string(index=False))